src/Entity/Opinions.php
<?php

namespace App\Entity;

use App\Repository\OpinionsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OpinionsRepository::class)]
class Opinions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 2, max: 255)]
    #[Assert\Regex("/^[-',;:.?!-'0-9a-zA-ZÀ-ÿ\s]+$/")]
    private ?string $opinion_message = null;

    #[ORM\Column]
    #[Assert\Regex("/^[1-5]$/")]
    private ?int $opinion_rate = null;

    #[ORM\Column(nullable: true)]
    private ?bool $opinion_is_validated = null;

    #[ORM\ManyToOne(inversedBy: 'user_opinions')]
    private ?Users $opinion_users = null;

    #[ORM\ManyToOne(inversedBy: 'recipe_opinions')]
    private ?Recipes $opinion_recipes = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOpinionMessage(): ?string
    {
        return $this->opinion_message;
    }

    public function setOpinionMessage(string $opinion_message): static
    {
        $this->opinion_message = $opinion_message;

        return $this;
    }

    public function getOpinionRate(): ?int
    {
        return $this->opinion_rate;
    }

    public function setOpinionRate(int $opinion_rate): static
    {
        $this->opinion_rate = $opinion_rate;

        return $this;
    }

    public function isOpinionIsValidated(): ?bool
    {
        return $this->opinion_is_validated;
    }

    public function setOpinionIsValidated(bool $opinion_is_validated): static
    {
        $this->opinion_is_validated = $opinion_is_validated;

        return $this;
    }

    public function getopinionUsers(): ?Users
    {
        return $this->opinion_users;
    }

    public function setopinionUsers(?Users $opinion_users): static
    {
        $this->opinion_users = $opinion_users;

        return $this;
    }

    public function getopinionRecipes(): ?Recipes
    {
        return $this->opinion_recipes;
    }

    public function setopinionRecipes(?Recipes $opinion_recipes): static
    {
        $this->opinion_recipes = $opinion_recipes;

        return $this;
    }
}

src/Entity/Recipes.php
<?php

namespace App\Entity;

use App\Repository\RecipesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: RecipesRepository::class)]
#[Vich\Uploadable]
class Recipes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $recipe_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $recipe_description = null;

    #[ORM\Column(nullable: true)]
    private ?int $recipe_prep_duration = null;

    #[ORM\Column(nullable: true)]
    private ?int $recipe_rest_duration = null;

    #[ORM\Column(nullable: true)]
    private ?int $recipe_cook_duration = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $recipe_ingredient = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $recipe_step = null;

    #[ORM\Column]
    private ?bool $recipe_is_public = null;

    #[ORM\OneToMany(targetEntity: Opinions::class, mappedBy: 'opinion_recipes')]
    private Collection $recipe_opinions;

    #[ORM\ManyToMany(targetEntity: Allergens::class, inversedBy: 'allergen_recipes')]
    private Collection $recipe_allergens;

    #[ORM\ManyToMany(targetEntity: Diets::class, inversedBy: 'diet_recipes')]
    private Collection $recipe_diets;

    /* VichUploader properties - START */
    #[Vich\UploadableField(mapping: 'recipes', fileNameProperty: 'recipeImageName', size: 'recipeImageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $recipeImageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $recipeImageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $recipeImageUpdatedAt = null;

    #[ORM\Column(length: 255)]
    private ?string $recipe_source = null;

    #[ORM\Column(length: 255)]
    private ?string $recipe_image_source = null;

    /* VichUploader properties - END */

    public function __construct()
    {
        $this->recipe_opinions = new ArrayCollection();
        $this->recipe_allergens = new ArrayCollection();
        $this->recipe_diets = new ArrayCollection();
    }


    public function __toString()
    {
        return $this->getRecipeTitle();
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecipeTitle(): ?string
    {
        return $this->recipe_title;
    }

    public function setRecipeTitle(string $recipe_title): static
    {
        $this->recipe_title = $recipe_title;

        return $this;
    }

    public function getRecipeDescription(): ?string
    {
        return $this->recipe_description;
    }

    public function setRecipeDescription(string $recipe_description): static
    {
        $this->recipe_description = $recipe_description;

        return $this;
    }

    public function getRecipePrepDuration(): ?int
    {
        return $this->recipe_prep_duration;
    }

    public function setRecipePrepDuration(?int $recipe_prep_duration): static
    {
        $this->recipe_prep_duration = $recipe_prep_duration;

        return $this;
    }

    public function getRecipeRestDuration(): ?int
    {
        return $this->recipe_rest_duration;
    }

    public function setRecipeRestDuration(?int $recipe_rest_duration): static
    {
        $this->recipe_rest_duration = $recipe_rest_duration;

        return $this;
    }

    public function getRecipeCookDuration(): ?int
    {
        return $this->recipe_cook_duration;
    }

    public function setRecipeCookDuration(?int $recipe_cook_duration): static
    {
        $this->recipe_cook_duration = $recipe_cook_duration;

        return $this;
    }

    public function getRecipeIngredient(): ?string
    {
        return $this->recipe_ingredient;
    }

    public function setRecipeIngredient(string $recipe_ingredient): static
    {
        $this->recipe_ingredient = $recipe_ingredient;

        return $this;
    }

    public function getRecipeStep(): ?string
    {
        return $this->recipe_step;
    }

    public function setRecipeStep(string $recipe_step): static
    {
        $this->recipe_step = $recipe_step;

        return $this;
    }

    public function isRecipeIsPublic(): ?bool
    {
        return $this->recipe_is_public;
    }

    public function setRecipeIsPublic(bool $recipe_is_public): static
    {
        $this->recipe_is_public = $recipe_is_public;

        return $this;
    }

    /**
     * @return Collection<int, Opinions>
     */
    public function getRecipeOpinions(): Collection
    {
        return $this->recipe_opinions;
    }

    public function addRecipeOpinion(Opinions $recipeOpinion): static
    {
        if (!$this->recipe_opinions->contains($recipeOpinion)) {
            $this->recipe_opinions->add($recipeOpinion);
            $recipeOpinion->setopinionRecipes($this);
        }

        return $this;
    }

    public function removeRecipeOpinion(Opinions $recipeOpinion): static
    {
        if ($this->recipe_opinions->removeElement($recipeOpinion)) {
            // set the owning side to null (unless already changed)
            if ($recipeOpinion->getopinionRecipes() === $this) {
                $recipeOpinion->setopinionRecipes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Allergens>
     */
    public function getRecipeAllergens(): Collection
    {
        return $this->recipe_allergens;
    }

    public function addRecipeAllergens(Allergens $recipeAllergens): static
    {
        if (!$this->recipe_allergens->contains($recipeAllergens)) {
            $this->recipe_allergens->add($recipeAllergens);
        }

        return $this;
    }

    public function removeRecipeAllergens(Allergens $recipeAllergens): static
    {
        $this->recipe_allergens->removeElement($recipeAllergens);

        return $this;
    }

    /**
     * @return Collection<int, Diets>
     */
    public function getRecipeDiets(): Collection
    {
        return $this->recipe_diets;
    }

    public function addRecipeDiets(Diets $recipeDiets): static
    {
        if (!$this->recipe_diets->contains($recipeDiets)) {
            $this->recipe_diets->add($recipeDiets);
        }

        return $this;
    }

    public function removeRecipeDiets(Diets $recipeDiets): static
    {
        $this->recipe_diets->removeElement($recipeDiets);

        return $this;
    }

    
    /* VichUploader methods - START */

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->recipeImageUpdatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setRecipeImageName(?string $recipeImageName): void
    {
        $this->recipeImageName = $recipeImageName;
    }

    public function getRecipeImageName(): ?string
    {
        return $this->recipeImageName;
    }

    public function setRecipeImageSize(?int $recipeImageSize): void
    {
        $this->recipeImageSize = $recipeImageSize;
    }

    public function getRecipeImageSize(): ?int
    {
        return $this->recipeImageSize;
    }

    /* VichUploader methods - END */

    public function getRecipeSource(): ?string
    {
        return $this->recipe_source;
    }

    public function setRecipeSource(string $recipe_source): static
    {
        $this->recipe_source = $recipe_source;

        return $this;
    }

    public function getRecipeImageSource(): ?string
    {
        return $this->recipe_image_source;
    }

    public function setRecipeImageSource(string $recipe_image_source): static
    {
        $this->recipe_image_source = $recipe_image_source;

        return $this;
    }


}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Opinions;
use App\Entity\Recipes;
use App\Entity\Users;
use App\Form\OpinionType;
use App\Repository\AllergensRepository;
use App\Repository\OpinionsRepository;
use App\Repository\RecipesRepository;
use App\Repository\UsersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Attribute\Route;

class RecipesController extends AbstractController
{
    #[Route('/recipes', name: 'app_recipes')]
    public function index(SessionInterface $session, AllergensRepository $allergensRepository, RecipesRepository $recipesRepository, Security $security, Request $request): Response
    {   
        // Current user
        $user = $security->getUser();

        // Session
        $session->set('previous_url', $request->getUri());
        
        // Allergens
        $allergens = $allergensRepository->findBy([],['id' => 'ASC']);
        
        $recipes = $recipesRepository->findBy([],['id' => 'ASC']);
        /* Filter function (not working) 
        $allergenId = $request->get('allergenId');
        $recipes = $recipesRepository->findRecipes($allergenId);
        */

        return $this->render('recipes/recipes_page.html.twig', [
            'controller_name' => 'RecipesController',
            'recipes' => $recipes,
            'user' => $user,
            'allergens' => $allergens,
        ]);
    }

    #[Route('/recipes/{id}', name: 'app_show_recipe')]
    public function show_recipe(Recipes $recipe, OpinionsRepository $opinionsRepository, Request $request, EntityManagerInterface $entManInt, Security $security) : Response
    {
        // Average rate : linked to OpinionsRepository.php function getAverageRateByRecipeID
        $averageRate = $opinionsRepository->getAverageRateByRecipeID($recipe->getId());

        // Current user
        $user = $security->getUser();

        // Existing opinions to display
        $opinions = $opinionsRepository->findBy(['opinion_recipes' => $recipe],['id' => 'ASC']);
        
        // Opinion asked to the current user in a form
        $opinion = $opinionsRepository->findOneBy(['opinion_recipes' => $recipe, 'opinion_users' => $user]);
        if (!$opinion) {    // Modification of the opinion if existing opinion for this recipe and this user
            $opinion = new Opinions();
            $opinion->setopinionRecipes($recipe);   // Current recipe
            $opinion->setopinionUsers($user);       // Current user
            $opinion->setOpinionIsValidated(false); // Opinion not validated by default
        }    

        $form = $this->createForm(OpinionType::class, $opinion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entManInt->persist($opinion);
            $entManInt->flush();

            $this->addFlash('success', 'Votre commentaire a bien été envoyé');

        }
        
        return $this->render('recipes/show_recipe_page.html.twig', [
            'controller_name' => 'RecipesController',
            'recipe' => $recipe,
            'opinions' => $opinions,
            'form' => $form,
            'user' => $user,
            'averageRate' => $averageRate,
        ]);
    }
}

templates/recipes/recipes_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Les recettes de Sandrine Coupart, diététicienne et nutritionniste - Les recettes
{% endblock %}

{% block body %}

  <main class='recipes_main'>

    <section class='recipes_section'>
      <h2 class='article_title'>Les recettes</h2>
      
      {% for recipe in recipes %}
        <article class='recipes_article'>
          <h4 class='recipes_title'>{{ recipe.recipetitle }}</h4>

          <div class='recipes_div'>
            {% if recipe.recipedescription != null %}
              <p class='recipes_text'>{{ recipe.recipedescription}}</p>
            {% endif %}

            {% if recipe.recipeImageName %}
              <img class='recipes_photo' src={{ vich_uploader_asset(recipe, 'imageFile') }} alt="Photo of the recipe : {{ recipe.recipetitle }}">
            {% else %}
              <img class='recipes_photo' src={{ asset('images/logo.svg') }} alt="Photo of the recipe by default - Image par Диана Кубенева de Pixabay">
            {% endif %}

            <div class='recipes_sources'>
              <ul> Sources
                <li>Image : {{ recipe.recipeimagesource }}</li>
                <li>Recette : <a class='recipes_sources' href={{ recipe.recipesource }} target="_blank">{{ recipe.recipesource }}</a></li>
              <ul>
            </div>            

            <!-- Page of the recipe -->
            <a class="link" href="{{ path('app_show_recipe', {'id': recipe.id}) }}">Voir la recette</a>
          </div>
        </article>
      {% endfor %}

    </section>

  </main>
  
{% endblock %}

templates/recipes/show_recipe_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Les recettes de Sandrine Coupart, diététicienne et nutritionniste - Page de la recette : {{ 'recipe' }}
{% endblock %}


{% block body %}

  <main class='recipe_main'>

  <article class="confirmation_article">
      {% for flashMessage in app.flashes('success') %}
          <div class="confirmation_div" role="alert">
              {{ flashMessage }}
          </div>
      {% endfor %}
    </article>

    <!-- Display of the recipe -->
    <section class='recipe_section'>
      {% include '/partials/recipes/_recipe_block.html.twig' %}
    </section>

    <aside class='recipe_aside'>
      <!-- Let a review for this recipe and for this user -->
      <article class='aside_article'>
        <h2 class='article_title'>Laisser un commentaire</h2>
          
          <div class='form_div'>
            {% if user %}
              {{ include('partials/opinion/_form.html.twig')}}   
            {% else %}
              <p>Vous devez être connecté pour pouvoir laisser un commentaire. 
              Rendez-vous sur la page <a href="{{ path('app_login')}}">Connexion</a>
            {% endif %}
          </div>
      </article>

      <!-- Display the average rate -->
      <article class='aside_article'>
        <h2 class='article_title'>Note moyenne de la recette</h2>
          
          <div class='average_rate_div'>
            <!-- Display of the average rate -->
            {% if averageRate %}
              <p>Note moyenne : {{ averageRate }}/5</p>
            {% else %}
              <p>Il n'y a pas encore de note</p>
            {% endif %}

          </div>
      </article>

      
      <section class='opinion_section'>
        <h2 class='article_title'>Les avis des patients</h2>

        <!-- Display the reviews of all users for this recipe -->   
        {% for opinion in opinions %}
          <article class='aside_article'>
            <h4 class='opinion_title'>{{ opinion.opinionusers}}</h4>
            <p>{{ opinion.opinionMessage}}</p>

            <div class='opinion_div'>
              
              <p>{{ opinion.opinionrate}}/5</p>
            </div>
            
          </article>
        {% endfor %}
      </section>
    </aside>

  </main>
  
{% endblock %}